config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :boards
  resources :postings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'boards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :postings
end

app/models/posting.rb
class Posting < ApplicationRecord
  belongs_to :board
  belongs_to :user

  paginates_per 10
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :postings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @postings = @board.postings.page(params[:page])
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name)
    end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  before_action :set_posting, only: [:show, :edit, :update, :destroy]

  # GET /postings
  # GET /postings.json
  def index
    if params[:all] == "true"
    @postings = Posting.all.page(params[:page])
    end
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
  end

  # GET /postings/new
  def new
    if params[:board_id]
    @board = Board.find(params[:board_id])
  end
    @posting = Posting.new
  end

  # GET /postings/1/edit
  def edit
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = Posting.new(posting_params)

    if params[:board_id]
      @posting.board_id = params[:board_id]
    end

    respond_to do |format|
      if @posting.save
        format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
        format.json { render :show, status: :created, location: @posting }
      else
        format.html { render :new }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /postings/1
  # PATCH/PUT /postings/1.json
  def update
    respond_to do |format|
      if @posting.update(posting_params)
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @posting }
      else
        format.html { render :edit }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting.destroy
    respond_to do |format|
      format.html { redirect_to postings_url, notice: 'Posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_posting
      @posting = Posting.find(params[:id])
      @author = User.find(@posting.user_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def posting_params
      params.require(:posting).permit(:title, :location, :content, :board_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :board_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.name %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

    <script type="text/javascript" src="https://static.filestackapi.com/v3/filestack.js"></script>
    <script>
        var client = filestack.init('ADJtRoEBORWC2hskhDZbDz');
        function showPicker() {
            client.pick({
            }).then(function(result) {
                console.log(JSON.stringify(result.filesUploaded))
            });
        }
    </script>
    <input type="button" value="Upload" onclick="showPicker()" />


  </tbody>
</table>

<br>

<%= link_to 'New Board', new_board_path %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @board.name %>
</p>

<p>
  <%= link_to "Post to #{@board.name}", new_posting_path(board_id: @board.id) %>
</p>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>
<td><%= link_to 'Show', @posting %></td>

  <tbody>
    <% @postings.each do |posting| %>
      <tr>
        <td><%= link_to posting.title, posting %></td>
        <td><%= posting.location %></td>

      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @postings %>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TTS P0st Here</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="header">
      <% if current_user %>
      Welcome <%= current_user.email %>!
      <% end %>

	<% if user_signed_in? %>
		<%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
	<% end %>

</div>

    <%= yield %>
  </body>
</html>

app/views/postings/_form.html.erb
<%= form_with(model: posting, local: true) do |form| %>
  <% if posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(posting.errors.count, "error") %> prohibited this posting from being saved:</h2>

      <ul>
      <% posting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :posting_title %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :posting_location %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :posting_content %>
  </div>

  <% if @board %>
    <%= form.hidden_field :board_id, value: @board.id %>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/postings/edit.html.erb
<h1>Editing Posting</h1>

<%= render 'form', posting: @posting %>

<%= link_to 'Show', @posting %> |
<%= link_to 'Back', postings_path %>

app/views/postings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Postings</h1>

<%= link_to 'All Postings',postings_path(all: "true") %>
<%= link_to 'First Posting', postings_path(all: "false") %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @postings.each do |posting| %>
      <tr>
        <td><%= posting.title %></td>
        <td><%= posting.location %></td>
        <td><%= posting.content %></td>
        <td><%= link_to 'Show', posting %></td>
        <td><%= link_to 'Edit', edit_posting_path(posting) %></td>
        <td><%= link_to 'Destroy', posting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @postings %>

app/views/postings/new.html.erb
<% if @board %>
  <h1>New Posting - <%= @board.name %></h1>
<% else %>
  <h1>New Posting</h1>
<% end %>

<%= render 'form', posting: @posting %>

<%= link_to 'Back', postings_path %>

app/views/postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @posting.location %>
</p>

<p>
  <strong>Title:</strong>
  <%= @posting.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @posting.content %>
</p>

<%= link_to 'Edit', edit_posting_path(@posting) %> |
<%= link_to 'Back', board_path(@posting.board_id) %>